version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-wally_web_1
      APP_PORT: 80

  web:
    image: poliuscorp/wally:1.14@sha256:3de5384092e6515248d45a924c4df276cd34a0b4d6480509dc21f3024c655360
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/wally/data
    environment:
      DEMO: "false"
